# Generated by Django 4.1.4 on 2023-08-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='I hope to connect with more people with similar interests', max_length=2000),
        ),
    ]
