# Generated by Django 4.1.4 on 2023-08-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
