# Generated by Django 4.1.4 on 2023-08-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_interests_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='I hope to connect with more people with similar interests', max_length=2000),
        ),
    ]
