# Generated by Django 4.1.4 on 2023-08-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='about',
            field=models.TextField(default='Lets talk about <django.db.models.fields.CharField>'),
        ),
    ]
