# Generated by Django 4.1.4 on 2023-08-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='about',
            field=models.TextField(default='Lets talk!'),
        ),
    ]
