# Generated by Django 4.1.4 on 2023-08-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatroom_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='about',
            field=models.TextField(default='Lets talk!', error_messages={'max_length': 'Your description is too long.'}, max_length=500),
        ),
    ]
